# Generated by Django 4.2.8 on 2023-12-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('update_add', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
