# Generated by Django 4.2.8 on 2023-12-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('update_add', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(null=True, upload_to='posts', verbose_name='Фото')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('rate', models.FloatField(default=0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'product',
            },
        ),
    ]
