# Generated by Django 4.2.8 on 2023-12-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
