# Generated by Django 4.2.8 on 2023-12-21 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('update_add', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.CharField(max_length=200, verbose_name='Категория')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Категория', to='blok.product', verbose_name='пост')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
