# Generated by Django 4.2.8 on 2023-12-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0003_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blok.product', verbose_name='пост'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('update_add', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.CharField(max_length=400, verbose_name='Отзыа')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='blok.product', verbose_name='отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'review',
            },
        ),
    ]
