# Generated by Django 4.2.8 on 2023-12-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0004_alter_category_post_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Категория'),
        ),
    ]
